version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./app:/app
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        working_dir: /app    
        volumes:
            - ./app:/app
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: secret123
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: gainiadb
        volumes:
            - mysqldata:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin:latest
        environment:
            PMA_HOST: mysql

        ports:
            - 8080:80
        restart: unless-stopped

volumes:
    mysqldata: {}
